### ISSUE TITLE
Issue with TensorFlow and Keras compatibility

### ISSUE THREAD

**Issue by mitushig3** [ISosnovik/nn4topopt#1]
I am currently a student working on a project in the field of Topology Optimization.As a first step in understanding the process, I am trying to run and reproduce some of the results you have got from the paper. However, I run into a lot of technical errors while running your GitHub codes on Jupyter Lab that trace back to errors in compatibility between TensorFlow and Keras versions. 

Here is my technical stack information:

1.	Currently using a Linux-based machine with docker image of TensorFlow and Keras as it is pre-installed. I have tried installing specific versions of known compatible combinations of both the software (eg. TensorFlow v.2.0 and Keras v.2.3 etc. ) but it does not work.
2.	Currently using the NIVIDIA DGX GPU cluster machine for training the dataset. 

I have used the available TensorFlow image from the NVIDIA NGC catalogue to build my container and have tried testing your code using Jupyter Lab. However, I still run into a bunch of compatibility issues. 

Could you please let me know the exact TensorFlow, Keras and Python versions that you used at the time of training in your project? That would then help me run the code and understand your results better.

**Comment by ISosnovik** [comment]
I don't remember exactly what version were used for the project. But they were up-to-date in early 2017. So you can check what TF and Keras were released around December 2016 - February 2017. 

What errors do you have?
Could you show some examples?

**Comment by asif1995malik** [comment]
I was having similar issues of those mentioned by mitushig3. (Also a student in attempting to understand this field further). 

I resolved such issues by:

**1.** Staying in TensorFlow 2.x but you can still use 1.x API by replacing:
`import tensorflow as tf`

with

```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```

**2.** Within data_utils.py changing line 1. to:
`from tensorflow.keras.utils import GeneratorEnqueuer`
As from my understanding; Tensorflow 2.x onward, keras is no longer maintained and it became a part of Tensorflow.
