### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by sun0912704** [ISosnovik/nn4topopt#2]
hello,Professior!
I have a problem in the first step--to generate the .h5 dataset.  To solve it , I have checked File System Permissions and ran as Administrator.  It also can't be solved.  Can you give me other ways to solve it?The error picture as the follow picture:
![image](https://github.com/ISosnovik/nn4topopt/assets/62976651/dbb9174f-ac1e-49af-a31c-75e8236241b5)

**Comment by ISosnovik** [comment]
Hello,

It is a Windows-specific error related to the read/write rights. I don't work with Windows, so I don't know the exact solution. 
Maybe you need to add permissions to `prepare_data.py`
