### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by sun0912704** [ISosnovik/nn4topopt#3]
Hello,

It is a Windows-specific error related to the read/write rights. I don't work with Windows, so I don't know the exact solution. 
Maybe you need to add permissions to `prepare_data.py`

_Originally posted by @ISosnovik in https://github.com/ISosnovik/nn4topopt/issues/2#issuecomment-2119343404_

**Comment by ISosnovik** [comment]
Have you solved the problem?

**Comment by sun0912704** [comment]
Yes,l have solved it.But l have a new question.I want to know how to get the IoU and how to test the model.
